-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 18:11:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc` DEFAULT CHARACTER SET utf8 ;
USE `mvc` ;

-- -----------------------------------------------------
-- Table `mvc`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`empresa` (
  `idpessoa` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(155) NOT NULL,
  `senha` VARCHAR(8) NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(155) NULL,
  PRIMARY KEY (`idpessoa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`funcionario` (
  `idfuncionario` INT NOT NULL,
  `nome` VARCHAR(155) NOT NULL,
  `pis` VARCHAR(11) NULL,
  `rg` VARCHAR(7) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `arquivo` VARCHAR(45) NOT NULL,
  `empresa_idpessoa` INT NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  INDEX `fk_funcionario_empresa_idx` (`empresa_idpessoa` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_empresa`
    FOREIGN KEY (`empresa_idpessoa`)
    REFERENCES `mvc`.`empresa` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
