-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 08:10:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mvc` DEFAULT CHARACTER SET utf8 ;
USE `mvc` ;

-- -----------------------------------------------------
-- Table `mvc`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`usuario` (
  `idusuario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `senha` VARCHAR(155) NOT NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `idpessoa_UNIQUE` (`idusuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvc`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mvc`.`funcionario` (
  `idfuncionario` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(155) NOT NULL,
  `pis` VARCHAR(11) NOT NULL,
  `rg` VARCHAR(7) NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `telefone` VARCHAR(10) NOT NULL,
  `email` VARCHAR(155) NOT NULL,
  `arquivo` VARCHAR(45) NULL,
  `usuario_idusuario` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idfuncionario`),
  UNIQUE INDEX `idfuncionario_UNIQUE` (`idfuncionario` ASC) VISIBLE,
  INDEX `fk_funcionario_usuario_idx` (`usuario_idusuario` ASC) VISIBLE,
  UNIQUE INDEX `usuario_idusuario_UNIQUE` (`usuario_idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_funcionario_usuario`
    FOREIGN KEY (`usuario_idusuario`)
    REFERENCES `mvc`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
